### ISSUE TITLE
[bug] only one recipe is served

### ISSUE THREAD

**Issue by purple-emily** [pvd-dev/InstaRecipe#1]
Load the [website](https://flask-service.vdotvo9a4e2a6.eu-central-1.cs.amazonlightsail.com/) and the only recipe is 

>  Drunk Dogs Recipe

If you press "get new recipe" the following stack trace is produced. 

```
KeyError
KeyError: 'value'

Traceback (most recent call last)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/instarecipe/app.py", line 89, in new
GetNewRecipe(); #Fetching the new recipe using the function
File "/instarecipe/app.py", line 33, in GetNewRecipe
ImageURL = (Image["value"][0]["url"])
KeyError: 'value'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by pvd-dev** [comment]
@purple-emily  Hey thanks for reporting! I think I ran into a rate limit with the image API. I upgraded to 1000 images per month now. Let me know if you find any other issues!
